# 고대의 성에서 🏰
숲을 지나 고대의 성에 도착한 당신. 성을 정복하기 위해 최종 도전 과제를 해결해야 합니다.

# [문제 1] **"마법 진주"**
### 원하는만큼 마법 진주를 만들어 낼 수 있는 항아리가 있습니다. 변수 `n`에 숫자를 저장하고, `1`부터 `n`까지의 합을 출력하세요.

In [18]:
n = 10
sum_n = sum(range(1, n+1))

print(sum_n)


55


# [문제 2] **"왕의 암호"**
### `kingdom` 변수에 여러개의 문자를 입력받아, 각 단어의 첫 글자만 대문자로 출력하세요.
### `kingdom`의 문자열에는 `queen`,`password`,`ozcodingschool`이 기본적으로 입력되어야 하며, 콤마(,)로 단어를 구분합니다.

In [31]:
# kingdom = input("암호를 입력하세요.").split(",")
kingdom = ["queen", "password", "ozcodingschool"]
print(kingdom[0][0].upper() + kingdom[0][1:], kingdom[1][0].upper() + kingdom[1][1:], kingdom[2][0].upper() + kingdom[2][1:])


## capitalize(), title() 함수 사용
# capitalize() : 맨 첫글자만 대문자로 변환
# title() : 알파벳 외의 문자(숫자, 특수기호, 띄어쓰기 등)로 나누어져 있는 영단어들의 첫글자를 모두 대문자로 ex) abc-edf => Abc-Edf
print(kingdom[0].capitalize(), kingdom[1].capitalize(), kingdom[2].capitalize(), sep=' ')
print(kingdom[0].title(), kingdom[1].title(), kingdom[2].title(), sep=' ')

Queen Password Ozcodingschool
Queen Password Ozcodingschool
Queen Password Ozcodingschool


# [문제 3] **"성의 열쇠"**
### `5x5`크기의 배열로 숫자 1부터 25까지를 출력하세요.

In [6]:
arr = [[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]]

# print(arr)


# 넘파이(numpy) 사용
import numpy as np
a = np.array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# [문제 4] **"최고의 마법사"**
### 여러 숫자를 입력받아 가장 큰 숫자와 가장 작은 숫자를 출력하세요.


In [22]:
nums = list(map(int, input("숫자를 입력해주세요.").split(",")))

print(f'입력하신 숫자는 {nums} 입니다.')
print(f'최대값 : {max(nums)}')
print(f'최소값 : {min(nums)}')

입력하신 숫자는 [3, 4, 2, 234] 입니다.
최대값 : 234
최소값 : 2


# [문제 5] **"숲 속의 빛나는 숫자"**
### 주어진 숫자가 소수인지 판별하세요.

In [32]:
nums = 3.4

if isinstance(nums, float):
    print(f'{nums}는 소수입니다.')
else:
    print(f'{nums}는 소수가 아닙니다.')


3.4는 소수입니다.


# [문제 6] **"왕의 보물 상자"**
### 리스트 `[10, 20, 15, 25, 30]`에서 20 이상인 숫자만 출력하세요.

In [33]:
nums = [10, 20, 15, 25, 30]

for i in nums:
    if i >= 20:
        print(i)

20
25
30


# [문제 7] **"마법사의 나침반"**
### 좌표를 입력받아 북쪽, 남쪽, 동쪽, 서쪽으로 나누어 출력하세요.

In [5]:
axis = ["동쪽", "서쪽", "남쪽", "북쪽"]
nums = input("좌표를 입력해주세요").split(",")

result = dict(zip(axis, nums))
print(result)


{'동쪽': '4', '서쪽': ' 5', '남쪽': ' 6', '북쪽': ' 7'}


# [문제 8] **"숲의 보물 지도"**
### 문자열 `Tresure Hunt`에서 공백을 제거하고 길이를 계산하세요.

In [37]:
txt = "Tresure Hunt"

text = txt.split()
text = ''.join(text)
print(text)
print(len(text))


TresureHunt
11


# [문제 9] **"숲 속의 마법사 대결"**
### 사용자로부터 두 숫자를 입력받아 최대공약수를 계산하세요.

In [43]:
num1, num2 = map(int, input("최대공약수 계산을 위한 숫자 2개를 입력해주세요. (쉼표로 구분해주세요.)").split(","))
nums_gcd = list()

for i in range(min(num1, num2), 0, -1):
    if num1 % i == 0 and num2 % i == 0:
        nums_gcd.append(i)

print(max(nums_gcd))


# 파이썬 math 라이브러리 사용
# import math
# num1, num2 = map(int, input("최대공약수 계산을 위한 숫자 2개를 입력해주세요. (쉼표로 구분해주세요.)").split(","))
# math.gcd(num1, num2)



16


# [문제 10] **"성의 마지막 방"**
### 리스트에 있는 숫자들을 모두 더한 값이 100 이상이면 `열림`을 출력하고, 그렇지 않으면 `닫힘`을 출력하세요.

In [46]:
nums = list(map(int, input("숫자를 입력해주세요. (쉼표로 구분해주세요.)").split(",")))
sum_nums = 0

for i in nums:
    sum_nums += i

if sum_nums >= 100:
    print(f'합계가 {sum_nums}로 문이 열립니다.')
else:
    print(f'합계가 {sum_nums}로 문이 닫힙니다.')


합계가 566로 문이 열립니다.
